### ISSUE TITLE
Outstanding shares in guide?

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/guide#33]
Since this guide is currently public, should we really include the # of outstanding shares? http://guide.learnersguild.org/Hiring-Documents/Guide-to-Your-Equity.html

Seems like that info should be internally visible but not public.

/cc @shereefb

**Comment by shereefb** [comment]
Since they don’t know the price per share, they can’t infer our valuation. 
David, what do you think?

—

Schedule time with me: http://pick.co/shereef

“Washing one's hands of the conflict between the powerful and the powerless means to side with the powerful, not to be neutral.” - Paulo Freire

“When they tell you to grow up, they mean stop growing.” ~ Tom Robbins

On November 9, 2015 at 5:24:39 AM, Tanner Welsh (notifications@github.com) wrote:

Since this guide is currently public, should we really include the # of outstanding shares? http://guide.learnersguild.org/Hiring-Documents/Guide-to-Your-Equity.html

Seems like that info should be internally visible but not public.

/cc @shereefb

**Comment by shereefb** [comment]
Shereef is right. The number of shares is not meaningful information unless
you also  know price per share. That said, if this guide is public, my
instinct would be to keep number of shares in a seperate place along with
other related questions we will eventually want to address to partners such
as "what is the strike price of my options?" So I agree it should be
internally visible but not public since there will eventually be other
related info that will be sensitive.

**Comment by tannerwelsh** [comment]
Ok. Until we have a defined, central place for this kind of financial information, I'm going to replace this with a "please email X for info".
